#!/bin/sh
#. "$(dirname "$0")/_/husky.sh"
#yarn lint --fix
#yarn format
#git add .




# Obtener el nombre de la rama actual
current_branch=$(git branch --show-current)

# Verificar si la rama actual es "develop"
if [ "$current_branch" != "develop" ]; then
    yarn lint --fix
    yarn format
    git add .
else
    echo "Estás en la rama develop."
    exit 0
fi
